version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=mnm

  influxdb:
    image: influxdb:1.2
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SERVER_ROOT_URL=https://localhost:3000"
      - "GF_SECURITY_ADMIN_PASSWORD=secret"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=mnm
      - USE_DOCKER=yes
      - INFLUXDB_URL=influxdb://root:root@influxdb:8086/test
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python manage.py worker
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=mnm
      - USE_DOCKER=yes
      - INFLUXDB_URL=influxdb://root:root@influxdb:8086/test
    volumes:
      - .:/app
