# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=15)),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
