# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('users', models.PositiveIntegerField(blank=True, null=True)),
                ('statuses', models.PositiveIntegerField(blank=True, null=True)),
                ('connections', models.PositiveIntegerField(blank=True, null=True)),
                ('open_registration', models.NullBooleanField()),
                ('up', models.NullBooleanField()),
            ],
        ),
    ]
