# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_auto_20170414_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
