# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_instance_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
