# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_auto_20170501_1719'),
        ('instances', '0004_instance_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='instance',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='releases.Release'),
        ),
    ]
