# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='_version',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='release',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='version_major',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='version_minor',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='version_patch',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
